# Site settings
name: Priscilla Kyei Danso
title: Priscilla Kyei Danso | Data Engineer
description: Build Data Warehouse, ETL Pipeline coupled with analysing customer transaction data to optimize data driven decision making
url: https://priscilla100.github.io/
baseurl: ''
email: priscillakyeidanso@gmail.com
cover: https://priscilla100.github.io/img/og.png
logo: https://priscilla100.github.io/img/emojis/technologist.png
resume: https://priscilla100.github.io/resume.pdf
social:
  - title: email
    url: mailto:priscillakyeidanso@gmail.com
  - title: twitter
    url: https://twitter.com/_ewurabena
  - title: instagram
    url: https://instagram.com/iam_scylla
  - title: codepen
    url: http://codepen.io/
  - title: github
    url: https://github.com/priscilla100
  - title: linkedin
    url: https://www.linkedin.com/in/priscilla-kyei-danso/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
