languages:
  - item: Python
  - item: PHP
  - item: HTML
  - item: CSS
  - item: SQL
  - item:
  - item:

frameworks:
  - item: Pandas
  - item: Scikit Learn
  - item: Apache Spark
  - item: Numpy
  - item: Seaborn
  - item: Matplotlib
  - item: BeautifulSoup

tools:
  - item: Bash
  - item: Git & Github & Bitbucket
  - item: AWS CLI
  - item: Google Big Query
  - item: DBeaver
  - item: Heroku
  - item: Postgresql
  - item: MySql

automation:
  - item: Jenkins
  - item: Ansible
  - item: Uwsgi
  - item: Nginx
  - item: Git & Github & Bitbucket


design:
  - item: Omnigraffle
  - item: Photoshop
  - item: Illustrator
  - item: User Testing

